[theme]

# Transparent so CSS background shows through
backgroundColor="rgba(0, 0, 0, 0.0)"
secondaryBackgroundColor="rgba(0, 0, 0, 0.0)"

# Text color â€“ light gray/white for readability
textColor="#fefefe"

# Accent (buttons, highlights, sliders)
primaryColor="#585303ff"